### ISSUE TITLE
I want to have possibility to send QEMU parameters via CLI

### ISSUE THREAD

**Issue by cynepco3hahue** [rmohr/qemu-dockerized#3]
For example it possible that you need more that 3Gi of memory, but to change it you need to edit QEMU command.

**Comment by rmohr** [comment]
Definitely. I guess I can make memory and cpu configurable, keep a static part and allow adding arbitrary extra qemu arguments.

**Comment by rmohr** [comment]
To illustrate the principle:
```bash
qemu-kvm -drive format=qcow2,file=${DISK}  \
  -device e1000,netdev=network0,mac=52:55:00:d1:55:${n} \
  -netdev tap,id=network0,ifname=tap${n},script=no,downscript=no \
  -vnc :${n} -enable-kvm -cpu host -m ${MEMORY} "$@"
```

Memory would be supplyable fia an env, the rest would go to qemu via "$@" after the static/generated part

**Comment by cynepco3hahue** [comment]
I think the additional useful item can be disk size.
